fix #9
m-messiah/ip2geo pull request #10
Opened 2018-02-26 14:10 UTC by AlexAkulov

2018-02-26 14:42 UTC, m-messiah requested changes
Отлично! Поправь мелкие замечания и докинь какой-нибудь токен в тестовое окружение, а то сейчас никак не тестируется.

2018-02-26 14:42 UTC, m-messiah commented on ip2proxy.go
> +func (o *ip2proxy) criteCompanies() error {
writeCompanies

2018-02-26 14:42 UTC, m-messiah commented on maxmind.go
>  		errors_chan <- Error{err, "MaxMind", "Download"}
А тут до errors_chan не дошли руки?

2018-02-26 14:42 UTC, m-messiah commented on utils.go
> +	bytes[0] = byte(ipnr & 0xFF)
Если тут for только намекает, то в ip2int уж явно просится

2018-02-26 15:33 UTC, chipitsine commented
токен же надо как-то зашифровать для travis?

(кроме токена, наверное, стоит документацию дописать)

2018-02-26 16:01 UTC, AlexAkulov commented on maxmind.go
>  		errors_chan <- Error{err, "MaxMind", "Download"}
Я решил сдержать себя что-бы не начать преписывать вообще всё.

2018-02-26 16:06 UTC, AlexAkulov commented
Не нужно какой-то токен. 
Нужно зарегаться там, поместить токен в переменные окружения трэвиса, а в тесте запускать ip2geo -ip2proxy-token=$MY_SECRET_TOKEN_IN_TRAVIS

2018-02-26 16:39 UTC, AlexAkulov commented on utils.go
> +	bytes[0] = byte(ipnr & 0xFF)
я не вижу в этом необходимости, будет 3 строчки вместо 4-х

2018-02-28 04:27 UTC, m-messiah commented
Докинул в переменные $IP2PROXY_TOKEN - добавь в тест.

2018-02-28 04:27 UTC, m-messiah commented on maxmind.go
>  		errors_chan <- Error{err, "MaxMind", "Download"}
ну вообще все не надо, но не логично переписать в одном файле, но не трогать в другом, при том, что обе правки к #9 никакого отношения не имеют

2018-03-01 05:06 UTC, chipitsine commented
У Travis переменные ведь недоступны из pull request веток?

2018-03-01 08:00 UTC, AlexAkulov commented
Я поправил errors_chan и удалил несипользуемый код. 
Макс, зарешай сам тесты, плз. Там не всё гладко с ними, например ip2proxy банит после какого-то колличества запрсов и тебе будет это проще сделать.

2018-03-01 17:01 UTC, m-messiah approved these changes

2018-03-01 17:58 UTC, merged

2018-03-01 18:29 UTC, m-messiah commented
После двух прогонов ip2location меня забанил, так что да, оставляем без теста.